# Generated by Django 3.1.6 on 2021-03-04 09:55

import ckeditor.fields
from django.db import migrations, models
import templated_email.fields


class Migration(migrations.Migration):

    dependencies = [
        ('templated_email', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('slug', templated_email.fields.AutoSlugField(blank=True, editable=False, populate_from='name', unique=True, verbose_name='Slug')),
                ('tempalte', ckeditor.fields.RichTextField(blank=True, help_text='The content of the mail. Context variable can be used.', null=True, verbose_name='tempalte')),
            ],
        ),
    ]
